CREATE TABLE CUSTOMERS (
userName VARCHAR NOT NULL,
customerName VARCHAR NOT NULL,
address VARCHAR NOT NULL,
creditCardDetails VARCHAR NOT NULL,
password VARCHAR NOT NULL,
CONSTRAINT PK_CUSTOMER PRIMARY KEY(userName)
);

CREATE TABLE PRODUCTS (
PRODUCTID INTEGER NOT NULL,
PRODUCTNAME VARCHAR NOT NULL,
DESCRIPTION VARCHAR NOT NULL,
CATEGORY VARCHAR NOT NULL,
PRICE DOUBLE NOT NULL,
QUANTITYINSTOCK DOUBLE NOT NULL,
CONSTRAINT PK_PRODUCTS PRIMARY KEY(PRODUCTID)
);

CREATE TABLE ORDERS (
orderId integer generated by default as identity (start with 1000) not null,
date timestamp not null,
customer varchar not null,
constraint pk_orders primary key (orderId),
constraint fk_orders_customers foreign key (customer) references customers(userName)
);

create table orderitems (
   orderId integer not null,
   productId varchar(255) not null,
   quantityPurchased double not null,
   constraint pk_orderitems primary key (orderId, productId),
   constraint fk_orderitems_orders foreign key (orderId) references orders(orderId),
   constraint fk_orderitems_products foreign key (productId) references products(productId)
);