CREATE TABLE PRODUCTS (
PRODUCTID INTEGER NOT NULL,
PRODUCTNAME VARCHAR NOT NULL,
DESCRIPTION VARCHAR NOT NULL,
CATEGORY VARCHAR NOT NULL,
PRICE DOUBLE NOT NULL,
QUANTITYINSTOCK DOUBLE NOT NULL,
CONSTRAINT PK_PRODUCTS PRIMARY KEY(PRODUCTID)
);