/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dao.InputValidationException;
import dao.OnlineDAO;
import dao.OnlineJdbcDAO;
import domain.Product;
import gui.helpers.SimpleListModel;
import java.awt.Window;
import javax.swing.JOptionPane;

/**
 *
 * @author devpu550
 */
public class ProductEditorDialog extends javax.swing.JDialog {
   
   private OnlineDAO dao = new OnlineJdbcDAO();
   private Product product = new Product();

   /**
    * Creates new form ProductEditorDialog
    */
   public ProductEditorDialog(java.awt.Window parent, boolean modal) {
      super(parent);
      super.setModal(modal);
      initComponents();
      //SimpleListModel model1 = new SimpleListModel(dao.getAllProducts());
      SimpleListModel model1 = new SimpleListModel(dao.getCategories());
      cmbCategory.setModel(model1);

   }
   
    public ProductEditorDialog(Window parent, boolean modal, Product product) {
      // delegate initialisation to other constructor
      this(parent, modal);
      this.product = product;
      txtProductId.setText(product.getProductId().toString());
      txtProductName.setText(product.getProductName());
      txtDescription.setText(product.getDescription());
      cmbCategory.setSelectedItem(product.getCategory());
      txtPrice.setText(product.getPrice().toString());
      txtQuantityInStock.setText(product.getQuantityInStock().toString());
      txtProductId.setEditable(false);
      
   }

   
   

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPane1 = new java.awt.ScrollPane();
        jSpinner1 = new javax.swing.JSpinner();
        scrollPane3 = new java.awt.ScrollPane();
        jSlider1 = new javax.swing.JSlider();
        lblProductId = new javax.swing.JLabel();
        lblProductName = new javax.swing.JLabel();
        lblDescription = new javax.swing.JLabel();
        lblCategory = new javax.swing.JLabel();
        lblPrice = new javax.swing.JLabel();
        lblQuantityInStock = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        txtProductId = new javax.swing.JTextField();
        txtProductName = new javax.swing.JTextField();
        cmbCategory = new javax.swing.JComboBox();
        txtPrice = new javax.swing.JTextField();
        txtQuantityInStock = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtDescription = new javax.swing.JTextArea();

        scrollPane1.setName("scrollPane1");

        jSpinner1.setName("jSpinner1");

        scrollPane3.setName("scrollPane3");

        jSlider1.setName("jSlider1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ProductEditorDialog");
        setName("ProductEditorDialog");

        lblProductId.setText("ID:");
        lblProductId.setName("lblProductId");

        lblProductName.setText("Name:");
        lblProductName.setName("lblProductName");

        lblDescription.setText("Description:");
        lblDescription.setName("lblDescription");

        lblCategory.setText("Category:");
        lblCategory.setName("lblCategory");

        lblPrice.setText("Price:");
        lblPrice.setName("lblPrice");

        lblQuantityInStock.setText("Quantity in Stock:");
        lblQuantityInStock.setName("lblQuantityInStock");

        btnSave.setText("Save");
        btnSave.setName("btnSave");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.setName("btnCancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        txtProductId.setName("txtProductId");

        txtProductName.setName("txtProductName");

        cmbCategory.setEditable(true);
        cmbCategory.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbCategory.setName("cmbCategory");

        txtPrice.setName("txtPrice");

        txtQuantityInStock.setName("txtQuantityInStock");

        jScrollPane3.setName("jScrollPane3");

        txtDescription.setColumns(20);
        txtDescription.setRows(5);
        txtDescription.setName("txtDescription");
        jScrollPane3.setViewportView(txtDescription);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(93, Short.MAX_VALUE)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblProductName)
                    .addComponent(lblProductId)
                    .addComponent(lblDescription)
                    .addComponent(lblCategory))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtProductId)
                    .addComponent(txtProductName)
                    .addComponent(cmbCategory, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblQuantityInStock)
                .addGap(18, 18, 18)
                .addComponent(txtQuantityInStock)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(lblPrice)
                .addGap(18, 18, 18)
                .addComponent(txtPrice)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtProductId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblProductId))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProductName)
                    .addComponent(txtProductName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDescription)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCategory)
                    .addComponent(cmbCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrice)
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQuantityInStock)
                    .addComponent(txtQuantityInStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnCancel))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
      // TODO add your handling code here:
      
     // if(txtProductId.getText().equals("") || txtPrice.getText().equals("") || txtQuantityInStock.getText().equals("")){
      //   JOptionPane.showMessageDialog(this,"you might have left the field empty. Please check again.","Input Error",JOptionPane.ERROR_MESSAGE);  
       //  return;
     // }
      
      try{
       product.setProductId(Integer.parseInt(txtProductId.getText()));
       product.setProductName(txtProductName.getText());
       product.setDescription(txtDescription.getText());
       product.setCategory((String) cmbCategory.getSelectedItem());
       product.setPrice(Double.parseDouble(txtPrice.getText()));  
       product.setQuantityInStock(Double.parseDouble(txtQuantityInStock.getText()));
       dao.save(product);
        this.dispose();
      } catch (InputValidationException ex) {
        
         String validationMessage = ex.getMessage();
         JOptionPane.showMessageDialog(this,validationMessage,"Input Error",JOptionPane.ERROR_MESSAGE);
         
      }catch (NumberFormatException ex){
         
         JOptionPane.showMessageDialog(this,"You must enter numbers. Please check again.","Input Error",JOptionPane.ERROR_MESSAGE);  
      }
   }//GEN-LAST:event_btnSaveActionPerformed

   private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
      // TODO add your handling code here:
      this.dispose();
   }//GEN-LAST:event_btnCancelActionPerformed

   /**
    * @param args the command line arguments
    */
   public static void main(String args[]) {
      /*
       * Set the Nimbus look and feel
       */
      //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
       * If Nimbus (introduced in Java SE 6) is not available, stay with the
       * default look and feel. For details see
       * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
       */
      try {
         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
               javax.swing.UIManager.setLookAndFeel(info.getClassName());
               break;
            }
         }
      } catch (ClassNotFoundException ex) {
         java.util.logging.Logger.getLogger(ProductEditorDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (InstantiationException ex) {
         java.util.logging.Logger.getLogger(ProductEditorDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (IllegalAccessException ex) {
         java.util.logging.Logger.getLogger(ProductEditorDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (javax.swing.UnsupportedLookAndFeelException ex) {
         java.util.logging.Logger.getLogger(ProductEditorDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      //</editor-fold>

      /*
       * Create and display the dialog
       */
      java.awt.EventQueue.invokeLater(new Runnable() {

         @Override
         public void run() {
            ProductEditorDialog dialog = new ProductEditorDialog(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {

               @Override
               public void windowClosing(java.awt.event.WindowEvent e) {
                  System.exit(0);
               }
            });
            dialog.setVisible(true);
         }
      });
   }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox cmbCategory;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JLabel lblCategory;
    private javax.swing.JLabel lblDescription;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblProductId;
    private javax.swing.JLabel lblProductName;
    private javax.swing.JLabel lblQuantityInStock;
    private java.awt.ScrollPane scrollPane1;
    private java.awt.ScrollPane scrollPane3;
    private javax.swing.JTextArea txtDescription;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtProductId;
    private javax.swing.JTextField txtProductName;
    private javax.swing.JTextField txtQuantityInStock;
    // End of variables declaration//GEN-END:variables
}
